version: '3.9'

services:
  postgres:
    image: postgres
    container_name: ${PROJECT_NAME}-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${PROJECT_NAME}_db
    ports:
      - 5432:5432
    volumes: 
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4
    container_name: ${PROJECT_NAME}-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8082:80